# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir X:/EC551/FinalProject/ec551_final29/ec551_final28.cache/wt [current_project]
set_property parent.project_path X:/EC551/FinalProject/ec551_final29/ec551_final28.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo x:/EC551/FinalProject/ec551_final29/ec551_final28.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/memory_part/gameover_palette.mem
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/memory_part/over_palette.mem
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/memory_part/gameover.mem
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/memory_part/over.mem
}
read_verilog -library xil_defaultlib {
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/DigitToSeg.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/new/FSR_button_controller.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/analog2game.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/imports/hdl/bg_gen.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/bram.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/clock_divider.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/counter3bit.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/debounce.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/dec_bcd.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/decoder3_8.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/end_capture.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/game.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/increment_one.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/menu_screen.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/mux4_4bus.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/num_hex.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/paddle.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/paddleh.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/score_to_7seg.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/segClkDevider.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/square.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/sram.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/start_square.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/top.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/topmodule.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/vga640x480.v
  X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/all_sources/top_Game.v
}
read_ip -quiet X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all x:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all x:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files X:/EC551/FinalProject/ec551_final29/ec551_final28.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_Game -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_Game.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_Game_utilization_synth.rpt -pb top_Game_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
